sudo: required

language: generic

services:
  - docker

before_install:
  - echo "Start creating docker image"
  - docker build --tag mingi0617/react-app:latest --file Dockerfile-dev .

script:
  - echo "Start running docker image"
  - docker run -e CI=true mingi0617/react-app npm run test -- --coverage

after_success:
  - echo "Test success"