sudo:              required

language:          generic

services:
  - docker

before_install:
  - echo "Start creating docker image"
  - docker build --tag mingi0617/react-app:latest --file Dockerfile-dev .

script:
  - echo "Start running docker image"
  - docker run -e CI=true mingi0617/react-app npm run test -- --coverage

after_success:
  - echo "Test success"

deploy:
  provider:    beanstalk
  region:      us-east-1
  app:         docker-react
  env:         Dockerreact-env
  bucket_name: elasticbeanstalk-us-east-1-533675935887
  bucket_path: docker-react
  on:
    branch: master

access_key_id:     $ACCESS_KEY_ID
secret_access_key: $SECRET_ACCESS_KEY